<Project>
  <Import Project="..\..\Directory.Build.props" />
  <PropertyGroup>
    <TargetFramework />
    <TargetFrameworks>net10.0;netstandard2.0;net472</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'HttpHybridCacheHandler.ContentStore'">
    <Compile Include="$(MSBuildThisFileDirectory)Compatibility\*.cs" Link="Compatibility\%(Filename)%(Extension)" />
    <Compile Include="$(MSBuildThisFileDirectory)Compatibility\IO\*.cs" Link="Compatibility\%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net472'">
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all"
                      Condition="'$(MSBuildProjectName)' != 'HttpHybridCacheHandler.ContentStore'" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
